-- 2AygB4OMxaKsfs0k
-- https://www.browserling.com/tools/mysql-password
CREATE USER 'cars'@'%' IDENTIFIED VIA mysql_native_password USING '*8B6083BA121308D66E42A169D4D6A562278337BA';
GRANT USAGE ON *.* TO 'cars'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `cars`;
GRANT ALL PRIVILEGES ON `cars`.* TO 'cars'@'%';
GRANT ALL PRIVILEGES ON `cars\_%`.* TO 'cars'@'%';